//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AycemOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public System.Guid OrderItemId { get; set; }
        public System.Guid OrderId { get; set; }
        public System.Guid ProductId { get; set; }
        public System.Guid ColourId { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Colour Colour { get; set; }
        public virtual Order Order { get; set; }
        public virtual Porduct Porduct { get; set; }
    }
}
